# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1cec80def906179fdb854b1c7477d5dd99a398792cd16d21d77895a9c7d32ff18b5a7369597c1a9299beb5f6e0edee840d0ea74a799949a588c1f04039e266a

test:
  secret_key_base: 743e992fda458ac757233be53ae00c5e5b20de0353079f59a5d370e9f3a902b3498fec85bde8e311a5b51a09ece704902e70a1a531bca7d6b1b85b49cdb6eac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
